;; This file is automatically generated by the multiple-cursors extension.
;; It keeps track of your preferences for running commands with multiple cursors.

(setq mc/cmds-to-run-for-all
      '(
		autopair-insert-opening
		autopair-insert-or-skip-quote
		autopair-newline
		autopair-skip-close-maybe
		c-electric-semi&comma
		c-indent-line-or-region
		keyboard-escape-quit
		kill-region
		))

(setq mc/cmds-to-run-once
      '(
		comment-region
		electric-newline-and-maybe-indent
		next-buffer
		xterm-paste
		))
